services:
  acestream-engine:
    image: jopsis/aceserve:latest
    container_name: acestream-engine
    restart: unless-stopped
    ports:
      - "6878:6878"
      - "8621:8621"
      - "62062:62062"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./config:/config

  proxy-app:
    build: .
    container_name: acestream-hdhr-proxy
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-5004}:${WEB_PORT:-5004}"
    environment:
      - ACESTREAM_URL=http://127.0.0.1:8888
      - DATA_DIR=/app/config
      - WEB_PORT=${WEB_PORT:-5004}
    volumes:
      - ./config:/app/config
    depends_on:
      - acestream-engine
