services:
  acestream-engine:
    image: vstavrinov/acestream-engine:latest
    container_name: acestream-engine
    restart: unless-stopped
    ports:
      - "6878:6878"
      - "8621:8621"
    volumes:
      - ./config:/config
    command: >
      /bin/bash -c "args=$$(cat /config/engine_args.txt 2>/dev/null || echo ''); mkdir -p /dev/shm/.ACEStream; ./start-engine --client-console --bind-all --live-cache-type memory $$args"

  acexy:
    image: ghcr.io/javinator9889/acexy:0.2.2
    container_name: acexy
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ACEXY_LISTEN_ADDR: ":8080"
      ACEXY_SCHEME: "http"
      ACEXY_HOST: "acestream-engine"
      ACEXY_PORT: "6878"
    depends_on:
      - acestream-engine

  proxy-app:
    build: .
    container_name: acestream-hdhr-proxy
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-5004}:${WEB_PORT:-5004}"
    environment:
      - ACESTREAM_URL=http://acexy:8080
      - DATA_DIR=/app/config
      - WEB_PORT=${WEB_PORT:-5004}
    volumes:
      - ./config:/app/config
    depends_on:
      - acexy
